### ISSUE TITLE
Is it possible to run the tests without UI injected?

### ISSUE THREAD

**Issue by Valdermeyder** [lambdaisland/kaocha-cljs2#10]
For CI or Git push hook cases the Chui UI is not needed at all, is it possible to run tests without it?

**Comment by plexus** [comment]
Yes

**Comment by Valdermeyder** [comment]
@plexus is it described somewhere? I have tried to understand how to do that but failed 😢

**Comment by plexus** [comment]
What are you doing now exactly? You don't need the chui UI for kaocha-cljs2, and you don't need kaocha-cljs2 to be able to use the Chui UI.

Chui consists of multiple pieces. The core test runner which is really just headless state and logic, and chui-ui or chui-remote to control it. You can use either or both. Kaocha-cljs2 only requires chui-remote.

With kaocha-cljs2 there are dozens of ways to wire things up, so you need to start telling me everything about your clojurescript and testing setup.

**Comment by plexus** [comment]
That all looks good. What is the behavior you are seeing?

The best place to start debugging is Funnel. Make sure funnel is started with verbose logging (`funnel -vv`), then you can see in fine detail what's going in between the browser and Kaocha.

**Comment by plexus** [comment]
Yes, just copy that namespace and tweak it?

https://github.com/lambdaisland/kaocha-cljs2/blob/master/src/kaocha/cljs2/shadow_runner.cljs#L29-L32

remove lines 6 and 29-32.

**Comment by alysbrooks** [comment]
I don't think this would be too difficult to document, but I'm not sure this is a workflow we want to prioritize documenting.

Feel free to ask further questions here or on Clojurians!
