### ISSUE TITLE
`:kaocha.type/cljs2` CPU load and performance

### ISSUE THREAD

**Issue by Valdermeyder** [lambdaisland/kaocha-cljs2#13]
The more tests I am adding the more often they are failing because of timeouts. 
### Background
I have started to write client tests using @testing-library and everything was quite okay in the beginning but after some time I have started to receive Timeout errors like the below one. 
```
Kaocha: Syntax error (ExceptionInfo) compiling at (/private/var/folders/86/2tqdp6j561z4z540d98w4ydw0000gp/T/form-init12547904487930344475.clj:1:126).
Timeout
```
I have increased the [wait time for @testing-library](https://testing-library.com/docs/dom-testing-library/api-configuration/#asyncutiltimeout) to 14000 and this helped to have them stable for some time.
It is worth adding that the lowest resources were on machines the more often I got those errors. Because of that I have stopped using `kaocha-cljs2` on CI and came back to karma there.
My Mac becomes very loud when I run tests and on the Activity Monitor, I can see how jvm and Chromium are taking most of the resources during the run (more than 100%)

The tests are not failing when Chui UI is used and I can easily run all of them there, but when I am trying to run them from the command line using kaocha `:type :kaocha.type/cljs2` and headless browser they are failing on one or another async test.

### Workaround
The one thing which helps me right now is splitting all my tests in chunks using `:skip-meta` and `:focus-meta` and run them one by one using `:kaocha.type/cljs2`

### Questions
Could it be that `:kaocha.type/cljs2` doesn't clean up properly between tests and keeps everything until the end of the run in either browser or jvm?

**Comment by humorless** [comment]
Hi @Valdermeyder , 

From your description "write client tests using [@testing-library](https://github.com/testing-library)", I feel somewhat difficult for me to reproduce this issue. Can you create a small repo that demonstrates the issue?

**Comment by Valdermeyder** [comment]
Sorry but I haven't been working with ClojureJs for a while and would not be able to create an example now.
Feel free to close the issue
