### ISSUE TITLE
chiu dependencies are outdated leading to outdated glogi

### ISSUE THREAD

**Issue by kommen** [lambdaisland/kaocha-cljs2#14]
https://github.com/lambdaisland/kaocha-cljs2/blob/2a3489ddb95ef7aa1716a7a8ca3d7c68aec9e641/deps.edn#L4-L5

Those lead to outdated glogi transient dependencies which are not compatible with latest ClojureScript/Closure Library versions.

**Comment by plexus** [comment]
Thanks, I'll try to get a new version released this week.

**Comment by or** [comment]
+1

The patch below worked for me, in case anyone else is blocked by this. `bin/proj install` creates a JAR in `target`, even tho the signing fails.
Note: I didn't dig very deep to find out whether these upgrades could break things. I didn't notice any problems, but my use case is rather small right now, so use with caution.
It's not included in the patch, but I also optimistically upgraded kaocha and clojurescript to the latest versions and didn't see any issues.
```patch
diff --git a/bin/proj b/bin/proj
index 6d45fcd..52425a4 100755
--- a/bin/proj
+++ b/bin/proj
@@ -4,8 +4,10 @@


 (lioss/main
- {:license        :mpl
+ {:group-id       "com.lambdaisland"
+  :license        :mpl
   :inception-year 2020
+  :name           "kaocha-cljs2"
   :description    "cljs.test support for Kaocha, second generation."})


diff --git a/deps.edn b/deps.edn
index 3c521bb..4377f42 100644
--- a/deps.edn
+++ b/deps.edn
@@ -1,8 +1,8 @@
 {:paths ["src" "resources"]

  :deps
- {lambdaisland/chui-remote {:mvn/version "0.0.156"}
-  lambdaisland/chui-ui     {:mvn/version "0.0.156"}
+ {lambdaisland/chui-remote {:mvn/version "1.1.192"}
+  lambdaisland/chui-ui     {:mvn/version "1.1.192"}
   io.pedestal/pedestal.log {:mvn/version "0.5.8"}}

  :aliases
```
