### ISSUE TITLE
clients need a way to control logging level with shadow runner

### ISSUE THREAD

**Issue by henryw374** [lambdaisland/kaocha-cljs2#34]
kaocha.cljs2.shadow-runner sets logging level to :all by default.

when the call is made to 
lambdaisland.chui.test-data/capture-test-data! the entirety of test info is printed to the console. This causes problems when there are a large number of tests - e.g. message is too large for channel when attached to chrome debugger. 

I don't see a way for clients to set the logging levels, other than writing a new runner ns similar to the shadow-runner.

**Comment by plexus** [comment]
People are encouraged to copy the runner namespace and modify to suit their needs. It's intended as a template.

**Comment by henryw374** [comment]
oh right ok. missed that. thanks
